name: Tests après un push sur la branche develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Test the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, sqlite3, bcmath, ctype, fileinfo, json, openssl, tokenizer, zip
          ini-values: post_max_size=256M, upload_max_filesize=256M
      - name: Création du fichier .env
        run: cp .env.example .env
      - name: Installation de Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar
          sudo chmod +x /usr/local/bin/composer
      - name: Installation des dépendances PHP
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Génération de la clé d'application
        run: php artisan key:generate
      - name: Exécution des migrations de la base de données
        run: php artisan migrate
      - name: Remplissage de la base de données
        run: php artisan db:seed
      - name: Installation des dépendances npm
        run: npm install
      - name: Construction des assets
        run: npm run build
      - name: Lancement des tests
        run: php artisan test